library(fixest)
library(data.table)
data <- read.csv("")
reg2 <- feols(log(Citation_Count) ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg1 <- feols(log(Citation_Count) ~ NIH |Year+JournalID+ FieldID2, data)
reg4 <- feols(log(Citation_Count) ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg3 <- feols(log(Citation_Count) ~ NSF |Year+JournalID+ FieldID2, data)
reg6 <- feols(log(C5+1) ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg5 <- feols(log(C5+1) ~ NIH |Year+JournalID+ FieldID2, data)
reg8 <- feols(log(C5+1) ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg7 <- feols(log(C5+1) ~ NSF |Year+JournalID+ FieldID2, data)
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7,reg8) , "")

reg2<- feols(log(Patent_Count+1) ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg6<- feols(log(Tweet_Count+1) ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg1<- feols(log(Patent_Count+1) ~ NIH |Year+JournalID+ FieldID2, data)
reg5<- feols(log(Tweet_Count+1) ~ NIH|Year+JournalID+ FieldID2, data)
reg4 <- feols(log(Patent_Count+1) ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg8 <- feols(log(Tweet_Count+1) ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg3<- feols(log(Patent_Count+1) ~ NSF |Year+JournalID+ FieldID2, data)
reg7 <- feols(log(Tweet_Count+1) ~ NSF|Year+JournalID+ FieldID2, data)
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7,reg8) , "")

reg2<- feols(nAtyp_10pct_Z_p ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg6<- feols(Disruption ~ NIH + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg1<- feols(nAtyp_10pct_Z_p ~ NIH |Year+JournalID+ FieldID2, data)
reg5<- feols(Disruption ~ NIH|Year+JournalID+ FieldID2, data)
reg4<- feols(nAtyp_10pct_Z_p ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg8<- feols(Disruption ~ NSF + log(Team_Size)+log(Institution_Count)+log(Country_Count)+log(Reference_Count)+RaoStirling+Hindex|Year+JournalID+ FieldID2, data)
reg3<- feols(nAtyp_10pct_Z_p ~ NSF |Year+JournalID+ FieldID2, data)
reg7<- feols(Disruption ~ NSF|Year+JournalID+ FieldID2, data)
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7,reg8) , "")